// this file is app/%28routes%29/dashboard/consultation/[consultationId]/page.tsx
"use client"
import React, { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Download, Printer, Share2, FileText } from 'lucide-react'

interface ConsultationData {
  consultationId: string
  transcription: string
  summary: string
  medicalPointers: string[]
  recommendations: string[]
  consultationDate: string
}

export default function ConsultationSummaryPage() {
  const params = useParams()
  const consultationId = params.consultationId as string
  const [consultation, setConsultation] = useState<ConsultationData | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    fetchConsultation()
  }, [consultationId])

  const fetchConsultation = async () => {
    try {
      const response = await fetch(`/api/consultation/${consultationId}`)
      if (response.ok) {
        const data = await response.json()
        setConsultation(data)
      }
    } catch (error) {
      console.error('Error fetching consultation:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const downloadReport = () => {
    if (!consultation) return

    const report = `
BATHUSI-AI MEDICAL CONSULTATION REPORT
=======================================

Consultation ID: ${consultation.consultationId}
Date: ${new Date(consultation.consultationDate).toLocaleDateString()}

SUMMARY:
${consultation.summary}

MEDICAL POINTERS:
${consultation.medicalPointers.map((pointer, index) => `${index + 1}. ${pointer}`).join('\n')}

RECOMMENDATIONS:
${consultation.recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

FULL TRANSCRIPTION:
${consultation.transcription}

---
Generated by Bathusi-AI Medical Assistant
    `.trim()

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `consultation-report-${consultation.consultationId}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white flex items-center justify-center">
        <div className="text-center">
          <FileText className="w-12 h-12 text-blue-500 mx-auto mb-4 animate-pulse" />
          <p>Loading consultation report...</p>
        </div>
      </div>
    )
  }

  if (!consultation) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white flex items-center justify-center">
        <div className="text-center">
          <FileText className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <p>Consultation not found</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white p-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex justify-between items-center mb-6">
          <div>
            <h1 className="text-3xl font-bold text-gray-800">Consultation Report</h1>
            <p className="text-gray-600">
              {new Date(consultation.consultationDate).toLocaleDateString()} • ID: {consultation.consultationId}
            </p>
          </div>
          <div className="flex space-x-2">
            <Button onClick={downloadReport} variant="outline">
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
            <Button onClick={() => window.print()} variant="outline">
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Summary Card */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Consultation Summary</CardTitle>
              <CardDescription>
                AI-generated summary of the doctor-patient conversation
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="prose max-w-none">
                <p className="text-gray-700 whitespace-pre-wrap">{consultation.summary}</p>
              </div>
            </CardContent>
          </Card>

          {/* Medical Pointers Card */}
          <Card>
            <CardHeader>
              <CardTitle>Medical Pointers</CardTitle>
              <CardDescription>
                Key points for doctor's consideration
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                {consultation.medicalPointers.map((pointer, index) => (
                  <li key={index} className="flex items-start">
                    <span className="text-blue-500 mr-2">•</span>
                    <span className="text-sm text-gray-700">{pointer}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Recommendations Card */}
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Recommendations</CardTitle>
              <CardDescription>
                Suggested next steps and follow-up actions
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-3">
                {consultation.recommendations.map((recommendation, index) => (
                  <li key={index} className="flex items-start p-3 bg-blue-50 rounded-lg">
                    <span className="bg-blue-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3 flex-shrink-0">
                      {index + 1}
                    </span>
                    <span className="text-sm text-gray-700">{recommendation}</span>
                  </li>
                ))}
              </ul>
            </CardContent>
          </Card>

          {/* Full Transcription Card */}
          <Card className="lg:col-span-3">
            <CardHeader>
              <CardTitle>Full Transcription</CardTitle>
              <CardDescription>
                Complete text of the recorded consultation
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="bg-gray-50 p-4 rounded-lg max-h-96 overflow-y-auto">
                <pre className="text-sm text-gray-700 whitespace-pre-wrap font-sans">
                  {consultation.transcription}
                </pre>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}